import fs from 'fs/promises'
import path from 'path'
import { parseSymbolsWithText } from '../differ/ast-differ.js'
import { findCodeFiles } from '../scanner/file-finder.js'
import { DocGenerateAgent } from '../agent/doc-generate-agent.js'
import { readFileOrEmpty } from '../utils/fs.js'
import { UTF8 } from '../constants.js'
import { GENERATE } from '../defaults.js'
import type { LLMClient } from '../llm/types.js'

export interface GenerateResult {
  readonly symbolCount: number
  readonly fileCount: number
  readonly outPath: string
}

export interface GenerateOptions {
  readonly codeDir: string
  readonly outPath: string
  readonly repoDir: string
  readonly projectTitle: string
  readonly projectDescription: string
  readonly client: LLMClient
  readonly model: string
  readonly concurrency?: number
}

/**
 * Generates API docs, llms.txt, and context7.json for a repo.
 * Writes docs to `outPath`, then writes llms.txt and context7.json to `repoDir`.
 */
export async function generateDocs(opts: GenerateOptions): Promise<GenerateResult> {
  const codeFiles = await findCodeFiles(opts.codeDir)
  if (codeFiles.length === 0) return { symbolCount: 0, fileCount: 0, outPath: opts.outPath }

  // Parse symbols with their source text from every code file
  const fileSymbols = await Promise.all(
    codeFiles.map(async file => {
      const source = await readFileOrEmpty(file)
      if (!source) return { file, symbols: [] }
      const symbols = await parseSymbolsWithText(source, file)
      return { file, symbols }
    }),
  )

  const nonEmpty = fileSymbols.filter(f => f.symbols.length > 0)
  if (nonEmpty.length === 0) return { symbolCount: 0, fileCount: 0, outPath: opts.outPath }

  const agent = new DocGenerateAgent(opts.client, opts.model)
  const limit = opts.concurrency ?? GENERATE.CONCURRENCY

  // Build flat task list preserving file→symbol association
  const tasks: Array<{ file: string; name: string; kind: string; run: () => Promise<string> }> = []
  for (const { file, symbols } of nonEmpty) {
    for (const sym of symbols) {
      tasks.push({
        file,
        name: sym.name,
        kind: sym.kind,
        run: () => agent.generateDoc({ symbol: sym.name, kind: sym.kind, file, sourceText: sym.text }),
      })
    }
  }

  const prose = await withConcurrency(tasks.map(t => t.run), limit)

  // Re-group by file for rendering
  const grouped = new Map<string, Array<{ name: string; kind: string; prose: string }>>()
  tasks.forEach((t, i) => {
    const list = grouped.get(t.file) ?? []
    list.push({ name: t.name, kind: t.kind, prose: prose[i] })
    grouped.set(t.file, list)
  })

  const markdown = renderApiDocs(grouped, opts.repoDir)
  await fs.mkdir(path.dirname(opts.outPath), { recursive: true })
  await fs.writeFile(opts.outPath, markdown, UTF8)

  await writeLlmsTxt(opts.repoDir, opts.outPath, opts.projectTitle, opts.projectDescription)
  await writeContext7Json(opts.repoDir, opts.outPath, opts.projectTitle, opts.projectDescription)

  return { symbolCount: tasks.length, fileCount: nonEmpty.length, outPath: opts.outPath }
}

// ─── Rendering ───────────────────────────────────────────────────────────────

function renderApiDocs(
  grouped: Map<string, Array<{ name: string; kind: string; prose: string }>>,
  repoDir: string,
): string {
  const date = new Date().toISOString().slice(0, 10)
  const lines: string[] = [
    '# API Reference',
    '',
    `> Generated by DocSync on ${date}. Updated automatically on every PR via [DocSync](https://github.com/Alok650/docsync).`,
    '',
  ]

  for (const [file, symbols] of grouped) {
    const rel = path.relative(repoDir, file)
    lines.push(`### \`${rel}\``, '')
    for (const { name, kind, prose } of symbols) {
      lines.push(`#### ${name}`, `*${kind}*`, '', prose, '')
    }
  }

  return lines.join('\n')
}

// ─── llms.txt ────────────────────────────────────────────────────────────────

async function writeLlmsTxt(
  repoDir: string,
  docsOutPath: string,
  title: string,
  description: string,
): Promise<void> {
  const docsRel = path.relative(repoDir, docsOutPath)
  const hasReadme = await fs.access(path.join(repoDir, 'README.md')).then(() => true).catch(() => false)
  const apiContent = await readFileOrEmpty(docsOutPath)
  const moduleGroups = extractModuleGroups(apiContent, docsRel)

  const lines: string[] = [
    `# ${title}`,
    '',
    `> ${description}`,
    '',
    '## Docs',
    '',
  ]

  if (hasReadme) {
    lines.push(
      '- [Overview & Quick Start](README.md): Installation, prerequisites, and a two-minute setup guide.',
      `- [Commands](README.md#commands): CLI reference — \`generate\`, \`init\`, \`check\`, \`symbols\`.`,
      `- [Configuration](README.md#configuration): Provider, model, and path overrides via config file.`,
      `- [GitHub Actions Workflow](README.md#github-actions-workflow): The generated workflow and required secrets.`,
      `- [Debugging](README.md#debugging): Common failure modes and fixes.`,
      `- [Full API Reference](${docsRel}): Symbol-level docs for every exported function, class, and type.`,
    )
  } else {
    lines.push(`- [API Reference](${docsRel}): Full API reference, generated and maintained by DocSync.`)
  }

  if (moduleGroups.length > 0) {
    lines.push('', '## Optional', '')
    for (const { label, link, summary } of moduleGroups) {
      lines.push(`- [${label}](${link}): ${summary}`)
    }
    lines.push('- [Source Code](src): TypeScript/JavaScript/Python source files.')
  } else {
    lines.push('', '## Optional', '- [Source Code](src): TypeScript/JavaScript/Python source files.')
  }

  await fs.writeFile(path.join(repoDir, 'llms.txt'), lines.join('\n') + '\n', UTF8)
}

interface ModuleGroup { label: string; link: string; summary: string }

function extractModuleGroups(apiContent: string, docsRel: string): ModuleGroup[] {
  // Parse level-3 headings that look like file paths: ### `src/foo/bar.ts`
  const fileHeadingRe = /^### `([^`]+)`$/gm
  const seen = new Set<string>()
  const groups: ModuleGroup[] = []

  for (const match of apiContent.matchAll(fileHeadingRe)) {
    const filePath = match[1]
    const parts = filePath.split('/')
    const topDir = parts.length >= 2 ? parts.slice(0, 2).join('/') : filePath
    if (seen.has(topDir)) continue
    seen.add(topDir)

    const label = toModuleLabel(topDir)
    const anchor = toGitHubAnchor(filePath)
    const summary = toModuleSummary(topDir)
    if (label) groups.push({ label, link: `${docsRel}${anchor}`, summary })
  }

  return groups
}

const MODULE_META: Record<string, { label: string; summary: string }> = {
  'src/agent':     { label: 'LLM Agents',          summary: 'DocGenerateAgent and DocUpdateAgent — LLM calls for doc generation and updates.' },
  'src/config':    { label: 'Configuration',        summary: 'DocSyncConfig schema and loadConfig — reading provider, model, and path settings.' },
  'src/cli':       { label: 'CLI',                  summary: 'Command definitions for generate, init, check, and symbols.' },
  'src/differ':    { label: 'Diffing',              summary: 'getGitDiff and diffSymbols — changed file and AST-level symbol detection.' },
  'src/editor':    { label: 'Document Editing',     summary: 'MarkdownEditor.replaceSection — in-place heading replacement in Markdown files.' },
  'src/extractor': { label: 'Symbol Extraction',    summary: 'Tree-sitter based extractor for TypeScript, JavaScript, and Python symbols.' },
  'src/generator': { label: 'Doc Generation',       summary: 'generateDocs pipeline — LLM-powered initial docs, llms.txt, and context7.json.' },
  'src/github':    { label: 'GitHub Integration',   summary: 'PR comment posting, context reading, and workflow file generation.' },
  'src/llm':       { label: 'LLM Clients',          summary: 'LLMClient interface and Anthropic/OpenAI adapters.' },
  'src/map':       { label: 'Symbol Map',           summary: 'buildMap and writeMapFile — the bidirectional symbol→doc index.' },
  'src/pipeline':  { label: 'CI Pipeline',          summary: 'runCheck — three-stage diff→lookup→LLM pipeline run in GitHub Actions.' },
  'src/scanner':   { label: 'File Scanner',         summary: 'findCodeFiles — discovers supported source files under a directory.' },
}

function toModuleLabel(topDir: string): string {
  return MODULE_META[topDir]?.label ?? ''
}

function toModuleSummary(topDir: string): string {
  return MODULE_META[topDir]?.summary ?? 'Source module.'
}

function toGitHubAnchor(filePath: string): string {
  const slug = filePath.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ +/g, '-')
  return `#${slug}`
}

// ─── context7.json ───────────────────────────────────────────────────────────

async function writeContext7Json(
  repoDir: string,
  docsOutPath: string,
  title: string,
  description: string,
): Promise<void> {
  const docsDir = path.relative(repoDir, path.dirname(docsOutPath))
  const config = {
    $schema: 'https://context7.com/schema/context7.json',
    projectTitle: title,
    description,
    folders: [docsDir],
    excludeFolders: ['.autodocs', 'node_modules', 'dist', '.git'],
  }
  await fs.writeFile(
    path.join(repoDir, 'context7.json'),
    JSON.stringify(config, null, 2) + '\n',
    UTF8,
  )
}

// ─── Concurrency limiter ─────────────────────────────────────────────────────

async function withConcurrency<T>(tasks: Array<() => Promise<T>>, limit: number): Promise<T[]> {
  const results: T[] = new Array(tasks.length)
  let next = 0

  async function worker(): Promise<void> {
    while (next < tasks.length) {
      const idx = next++
      results[idx] = await tasks[idx]()
    }
  }

  await Promise.all(Array.from({ length: Math.min(limit, tasks.length) }, worker))
  return results
}
