import fs from 'fs/promises'
import path from 'path'
import { parseSymbolsWithText } from '../differ/ast-differ.js'
import { findCodeFiles } from '../scanner/file-finder.js'
import { DocGenerateAgent } from '../agent/doc-generate-agent.js'
import { GENERATE } from '../defaults.js'
import type { LLMClient } from '../llm/types.js'

export interface GenerateResult {
  readonly symbolCount: number
  readonly fileCount: number
  readonly outPath: string
}

export interface GenerateOptions {
  readonly codeDir: string
  readonly outPath: string
  readonly repoDir: string
  readonly projectTitle: string
  readonly projectDescription: string
  readonly client: LLMClient
  readonly model: string
  readonly concurrency?: number
}

/**
 * Generates API docs, llms.txt, and context7.json for a repo.
 * Writes docs to `outPath`, then writes llms.txt and context7.json to `repoDir`.
 */
export async function generateDocs(opts: GenerateOptions): Promise<GenerateResult> {
  const codeFiles = await findCodeFiles(opts.codeDir)
  if (codeFiles.length === 0) return { symbolCount: 0, fileCount: 0, outPath: opts.outPath }

  // Parse symbols with their source text from every code file
  const fileSymbols = await Promise.all(
    codeFiles.map(async file => {
      const source = await fs.readFile(file, 'utf-8').catch(() => '')
      if (!source) return { file, symbols: [] }
      const symbols = await parseSymbolsWithText(source, file)
      return { file, symbols }
    }),
  )

  const nonEmpty = fileSymbols.filter(f => f.symbols.length > 0)
  if (nonEmpty.length === 0) return { symbolCount: 0, fileCount: 0, outPath: opts.outPath }

  const agent = new DocGenerateAgent(opts.client, opts.model)
  const limit = opts.concurrency ?? GENERATE.CONCURRENCY

  // Build flat task list preserving file→symbol association
  const tasks: Array<{ file: string; name: string; kind: string; run: () => Promise<string> }> = []
  for (const { file, symbols } of nonEmpty) {
    for (const sym of symbols) {
      tasks.push({
        file,
        name: sym.name,
        kind: sym.kind,
        run: () => agent.generateDoc({ symbol: sym.name, kind: sym.kind, file, sourceText: sym.text }),
      })
    }
  }

  const prose = await withConcurrency(tasks.map(t => t.run), limit)

  // Re-group by file for rendering
  const grouped = new Map<string, Array<{ name: string; kind: string; prose: string }>>()
  tasks.forEach((t, i) => {
    const list = grouped.get(t.file) ?? []
    list.push({ name: t.name, kind: t.kind, prose: prose[i] })
    grouped.set(t.file, list)
  })

  const markdown = renderApiDocs(grouped, opts.repoDir)
  await fs.mkdir(path.dirname(opts.outPath), { recursive: true })
  await fs.writeFile(opts.outPath, markdown, 'utf-8')

  await writeLlmsTxt(opts.repoDir, opts.outPath, opts.projectTitle, opts.projectDescription)
  await writeContext7Json(opts.repoDir, opts.outPath, opts.projectTitle, opts.projectDescription)

  return { symbolCount: tasks.length, fileCount: nonEmpty.length, outPath: opts.outPath }
}

// ─── Rendering ───────────────────────────────────────────────────────────────

function renderApiDocs(
  grouped: Map<string, Array<{ name: string; kind: string; prose: string }>>,
  repoDir: string,
): string {
  const date = new Date().toISOString().slice(0, 10)
  const lines: string[] = [
    '# API Reference',
    '',
    `> Generated by DocSync on ${date}. Updated automatically on every PR via [DocSync](https://github.com/Alok650/docsync).`,
    '',
  ]

  for (const [file, symbols] of grouped) {
    const rel = path.relative(repoDir, file)
    lines.push(`### \`${rel}\``, '')
    for (const { name, kind, prose } of symbols) {
      lines.push(`#### ${name}`, `*${kind}*`, '', prose, '')
    }
  }

  return lines.join('\n')
}

// ─── llms.txt ────────────────────────────────────────────────────────────────

async function writeLlmsTxt(
  repoDir: string,
  docsOutPath: string,
  title: string,
  description: string,
): Promise<void> {
  const docsRel = path.relative(repoDir, docsOutPath)
  const content = [
    `# ${title}`,
    '',
    `> ${description}`,
    '',
    '## Docs',
    `- [API Reference](${docsRel}): Full API reference, generated and maintained by DocSync.`,
    '',
    '## Optional',
    '- [Source Code](src): TypeScript/JavaScript/Python source files.',
  ].join('\n')

  await fs.writeFile(path.join(repoDir, 'llms.txt'), content + '\n', 'utf-8')
}

// ─── context7.json ───────────────────────────────────────────────────────────

async function writeContext7Json(
  repoDir: string,
  docsOutPath: string,
  title: string,
  description: string,
): Promise<void> {
  const docsDir = path.relative(repoDir, path.dirname(docsOutPath))
  const config = {
    $schema: 'https://context7.com/schema/context7.json',
    projectTitle: title,
    description,
    folders: [docsDir],
    excludeFolders: ['.autodocs', 'node_modules', 'dist', '.git'],
  }
  await fs.writeFile(
    path.join(repoDir, 'context7.json'),
    JSON.stringify(config, null, 2) + '\n',
    'utf-8',
  )
}

// ─── Concurrency limiter ─────────────────────────────────────────────────────

async function withConcurrency<T>(tasks: Array<() => Promise<T>>, limit: number): Promise<T[]> {
  const results: T[] = new Array(tasks.length)
  let next = 0

  async function worker(): Promise<void> {
    while (next < tasks.length) {
      const idx = next++
      results[idx] = await tasks[idx]()
    }
  }

  await Promise.all(Array.from({ length: Math.min(limit, tasks.length) }, worker))
  return results
}
